project_id = "gukvkyekmmdlmliomxtj"

[auth]
enabled = true
site_url = "https://d86949cc-ef18-4826-bd11-7b214db703f3.lovableproject.com"
additional_redirect_urls = ["http://localhost:5173/**", "https://preview--paperpusher.lovable.app", "https://d86949cc-ef18-4826-bd11-7b214db703f3.lovableproject.com/auth/v1/callback", "https://d86949cc-ef18-4826-bd11-7b214db703f3.lovableproject.com/**", "https://id-preview--d86949cc-ef18-4826-bd11-7b214db703f3.lovable.app/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400