// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gukvkyekmmdlmliomxtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1a3ZreWVrbW1kbG1saW9teHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NDg3MDYsImV4cCI6MjA1MzMyNDcwNn0.zlEKMxFEFlTBu4ePr_gSVes4s0ZMhTbQe-V9jxiQflg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);